source :rubygems
gem 'json'
gem 'hpricot', '0.8.4'
gem 'haml', '3.1.3'
gem 'oulu'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-r18n'
gem 'rack-flash3'
gem 'thin', '1.2.11'
gem 'eventmachine'
gem 'rack'
gem 'sinatra-asset-pipeline', require: 'sinatra/asset_pipeline'
gem 'sprockets-helpers'
gem 'uglifier'
gem 'autoprefixer-rails'
